### ISSUE TITLE
Users can reach routes even if they are not signed up

### ISSUE THREAD

**Issue by aviadhahami** [aviadhahami/ISCA-IDC#56]
Hey, 
I've reached `dashboard` and `application-form` without any user object.
We need to create a resolve in each state that verifies this data or kicks the user out.

assigned to @ShayGoldman

**Comment by aviadhahami** [comment]
@ShayGoldman please update here

**Comment by aviadhahami** [comment]
lol fuk dis

**Comment by mrsufgi** [comment]
Ggwp
